version: '3'

volumes:
  amplet_keys:
  amplet_rabbit:
  collector_rabbit:

services:
    # === Amp stuff ===
  amplet:
    #build: amplet2
    image: tylermarr/ampletest
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
    network_mode: host
    volumes:
      - "amplet_keys:/etc/amplet2/keys"
      - "amplet_rabbit:/var/lib/rabbitmq"
    extra_hosts: 
      - "amp-collector:163.7.137.27"
    environment: 
      - "RUN_AMP=go"



  collector:
    build: collector
    # hostname: amp-collector
    network_mode: host
    ports:
      - "80:80"       # Web view
      - "8086:8086"   # InfluxDB API
      - "5432:5432"   # PostgreSQL API
      - "61234:61234" # Client API
      # - "7655:7655"   # Ampca
      # - "5671:5673"   # Rabbitmq
      # - "443:443"     # Collectorcollector
    # volumes:
    #   - "collector_rabbit:/var/lib/rabbitmq"

