version: '3'

volumes:
  amplet_config:
  amplet_rabbit:
  collector_rabbit:
  collector_postgre:
  collector_influx:
  nntsc_config:
  amppki_config:
  grafana_config:

  #hdfs_data:

networks:
  amplets:
  grafana:
  flink_cluster:
  hdfs_cluster:

services:
    # === Amp stuff ===
  amplet:
    build: amplet2
    hostname: amplet
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
    networks:
      - amplets
    ports:
      #- "8869:8869"   # amplet control
      - "15672:15672" # rabbitmq management ui
    volumes:
      - "amplet_config:/etc/amplet2"
      - "amplet_rabbit:/var/lib/rabbitmq"
      - "amppki_config:/etc/amppki:ro"

  collector:
    build: collector
    hostname: collector
    networks:
      - amplets
      - grafana
      - flink_cluster
    ports:
      - "15671:15672" # rabbit management ui
      - "80:80"       # apache - ampweb
      #- "7655:7655"   # ampca
      #- "5672:5672"   # rabbit
      #- "5671:5671"   # rabbit ssl
      #- "61234:61234" # nntsc
      - "8086:8086"   # influxdb
      - "5432:5432"   # postgresql
      - "11211:11211" # memcached
    volumes:
      - "collector_rabbit:/var/lib/rabbitmq"
      - "collector_postgre:/var/lib/postgresql"
      - "collector_influx:/var/lib/influxdb"
      - "nntsc_config:/etc/nntsc"
      - "amppki_config:/etc/amppki"

    # === Just grafana ===
  grafana:
    build: grafana
    hostname: grafana
    networks:
      - grafana
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=guest"
    ports:
      - "3000:3000"   # grafana ui
    volumes:
      - "grafana_config:/var/lib/grafana"

    # === Flink stuff ===

  jobmanager:
    build: flink
    command: jobmanager
    #expose:
    #  - "6123"      # RPC port
    ports:
      - "8081:8081" # Web client
    networks:
      - flink_cluster
      - hdfs_cluster
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - "./flink/log4j-console.properties:/opt/flink/conf/log4j-console.properties"
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./flink/amp-analyser.properties:/opt/flink/conf/amp-analyser.properties"
      - "./datasets/:/opt/flink/data"

  taskmanager:
    build: flink
    command: taskmanager
    #expose:
      #- "6121"      # Data port
      #- "6122"      # RPC port
    networks:
      - flink_cluster
      - hdfs_cluster
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - "./flink/log4j-console.properties:/opt/flink/conf/log4j-console.properties"
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./flink/amp-analyser.properties:/opt/flink/conf/amp-analyser.properties"
      - "./datasets/:/opt/flink/data"

    # === Hadoop stuff ===
  hdfs-master:
    build: hadoop
    networks:
      - hdfs_cluster
    ports:
      - "50070:50070"   # Namenode web
    expose:
      - "9000"   # API port
    command: /start-namenode

  hdfs-slave:
    build: hadoop
    networks:
      - hdfs_cluster
    environment:
      - "NAMENODE_URI=hdfs://hdfs-master:9000"
    command: /start-datanode
