version: '3'

volumes:
  amplet_keys:
  amplet_rabbit:
  collector_rabbit:
  collector_postgre:
  collector_influx:
  nntsc_config:
  amppki_config:
  grafana_config:

networks:
  amplets:
  grafana:
  flink_cluster:
  hdfs_cluster:

services:
    # === Amp stuff ===
  amplet:
    build: amplet2
    hostname: amplet
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
    networks:
      - amplets
    volumes:
      - "amplet_keys:/etc/amplet2/keys"
      - "amplet_rabbit:/var/lib/rabbitmq"
      - "amppki_config:/etc/amppki:ro"

  collector:
    build: collector
    hostname: collector
    networks:
      - amplets
      - grafana
      - flink_cluster
    ports:
      - "80:80"       # Web view
      - "8086:8086"   # InfluxDB API
      - "5432:5432"   # PostgreSQL API
      - "61234:61234" # Client API
    volumes:
      - "collector_rabbit:/var/lib/rabbitmq"
      - "collector_postgre:/var/lib/postgresql"
      - "collector_influx:/var/lib/influxdb"
      - "nntsc_config:/etc/nntsc"
      - "amppki_config:/etc/amppki"

    # === Just grafana ===
  grafana:
    build: grafana
    hostname: grafana
    networks:
      - grafana
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=guest"
    ports:
      - "3000:3000"   # Grafana web
    volumes:
      - "grafana_config:/var/lib/grafana"

    # === Flink stuff ===

  jobmanager:
    build: flink
    command: jobmanager
    ports:
      - "8081:8081" # Flink web
    networks:
      - flink_cluster
      - hdfs_cluster
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - "./flink/log4j-console.properties:/opt/flink/conf/log4j-console.properties"
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./flink/streamevmon.properties:/opt/flink/conf/streamevmon.properties"
      - "./datasets/:/opt/flink/data"

  taskmanager:
    build: flink
    command: taskmanager
    networks:
      - flink_cluster
      - hdfs_cluster
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - "./flink/log4j-console.properties:/opt/flink/conf/log4j-console.properties"
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./flink/streamevmon.properties:/opt/flink/conf/streamevmon.properties"
      - "./datasets/:/opt/flink/data"

    # === Hadoop stuff ===
  hdfs-master:
    build: hadoop
    networks:
      - hdfs_cluster
    ports:
      - "50070:50070"   # Namenode web
    command: /start-namenode

  hdfs-slave:
    build: hadoop
    networks:
      - hdfs_cluster
    environment:
      - "NAMENODE_URI=hdfs://hdfs-master:9000"
    command: /start-datanode
