FROM flink:1.9.0-scala_2.12

ADD --chown=flink \
    https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-7.0/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar \
    /opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar